name: Run AI Script

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install @google/genai
      working-directory: ./
      
    - name: Run AI script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: node scripts/ai_query.js
      
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/ai_output.txt
        git diff --quiet && git diff --staged --quiet || git commit -m "Update AI output [skip ci]"
        git push
