# .github/workflows/translate.yml
name: Manual Translation Workflow

on:
  workflow_dispatch:
    inputs:
      json_url:
        description: 'URL of the JSON file to translate'
        required: true
        default: 'https://github.com/YuushaExa/crawl/raw/refs/heads/main/results/288571.json'

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @google/generative-ai axios

      - name: Create result folder
        run: mkdir -p result

      - name: Run translation script
        run: node scripts/translate.js
        env:
          JSON_URL: ${{ github.event.inputs.json_url }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
